### ISSUE TITLE
Add API documentation 

### ISSUE THREAD

**Issue by chrislaughlin** [chrislaughlin/useFetch#2]
Currently the README file has very limited docs. Add API docs that describe that can be passed to `useFetch` and what gets returned

**Comment by JCustin** [comment]
Hi, are you still looking for API documentation? I've looked over your documentation and I believe I can write them out. 

I just have a question regarding the content that can be passed through `useFetch`, notably is this request for any type of data? Or is it specifically meant for geographic data like your current example shows?

**Comment by chrislaughlin** [comment]
Thanks for picking this up. 

So the current readme is just code examples I used when testing. 

I would like to a have list of the API options this current is 
- URL: the URL used for the fetch call 
- options: This is optional and contains a mix of custom options and standard fetch options, you can see examples [here](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) 
- The custom options for this lib are as follows, These are passed in with the other fetch options
    - timeout: number of milliseconds before aborting the fetch 

I would like to see what is returned when you call useFetch e.g.
- isLoading,
- error,
- data,
- abortController
 
If you have any more questions let me know

**Comment by JCustin** [comment]
Hey Chris,

I've sent in a proposal for the revised README doc. I offered brief explanations for my revisions, and I hope you find them informative and representative. If I've misunderstood a concept, or you believe I should add new bits of information, please let me know! 

As a side question, would you mind if I used this work in my professional portfolio? I'll be sure to block any trace back to your name, if you'd prefer. I'd just like to record my revisions in documentation compared to the original doc.

**Comment by chrislaughlin** [comment]
Hey @JCustin  I don't see any PR for the changes have you raised one? 

Also you can use this for your portfolio 100% and it's fine to link back to me. If I can help in any way let me know

**Comment by JCustin** [comment]
Ah, sorry about that. I raised a pull request just now. 

And thank you for letting me use this work, I really appreciate it!
